### ISSUE TITLE
Question: Have you successfully produced 4k60 on any board?

### ISSUE THREAD

**Issue by teknoman117** [hdl-util/hdmi#13]
Hello,

I noticed you listed the pixel clocks for 4k60, but I was curious if you know of any boards capable of generating that signal. I'm looking at an Artix-7 and using the GTP engines. I've got a bit of a side project trying to build my own graphics card for retro computers (ISA bus and all), and I wanted to possibly product a 4k60 output on the board. (It would be integer scaling of whatever mode the old computer set, also a higher resolution helps emulate non-square pixels).

It would also be neat to do soundblaster emulation and pass it out over HDMI, but I'm looking to stay within the DVI spec because I don't think I'd have enough interest to warrant licensing HDMI.

**Comment by sameer** [comment]
> I noticed you listed the pixel clocks for 4k60,

4k60 is only available in HDMI 2.0 but haven't gotten around to implementing it. The libgen link to the spec is in the README if you're interested.

> I was curious if you know of any boards capable of generating that signal.

Unfortunately, none that I know of. The pixel clock is within reach of FPGAs: "For TMDS Character Rates above 340 Mcsc, the TMDS Clock Rate shall be one fourth (1/4) of the TMDS Character Rate. " which means you can use the same clock for 4k60 as you would for 1080p60 (148.5 MHz).

But you'll need to drive the remaining TMDS lines at 6Ghz (3 with double data rate) which can probably only be done with some specialized hardware.

> It would also be neat to do soundblaster emulation and pass it out over HDMI, but I'm looking to stay within the DVI spec because I don't think I'd have enough interest to warrant licensing HDMI.

If it's just for a personal project, I think you should be fine using HDMI. The licensing is primarily for if you plan to market/sell products to end consumers. You could try using Display Port instead since the standard itself is free. I haven't seen a board with display port before but maybe there is one.
